[package]
name = "test-project"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true
panic = "abort"
lto = "fat"
# overflow-checks = true

[build-dependencies]
cc = { version = "1.0" }

[dependencies]
